# See the following for information on how to setup the Python workflow for a
# single version:
# https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions

name: Validation Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v2

    - name: Setup Git Repos
      run: |
        cd ..
        git clone https://github.com/bxparks/UnixHostDuino
        git clone https://github.com/bxparks/AUnit
        git clone https://github.com/eggert/tz
        git clone https://github.com/HowardHinnant/date

    - name: Set up Hinnant Date
      run: |
        sudo apt update
        sudo apt install -y cmake libcurl4-openssl-dev
        cd tools/compare_cpp
        make

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'

    - name: Display Python version
      run: python -c "import sys; print(sys.version)"

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r tools/requirements.txt

    - name: Build Validation Tests
      run: |
        make -C tests/validation/BasicHinnantDateTest
        make -C tests/validation/ExtendedHinnantDateTest
        make -C tests/validation/BasicPythonTest
        make -C tests/validation/ExtendedPythonTest
        make -C tests/validation/BasicDateUtilTest
        make -C tests/validation/ExtendedDateUtilTest

    - name: Run Validation Tests
      run: |
        make -C tests/validation/BasicHinnantDateTest runtests
        make -C tests/validation/ExtendedHinnantDateTest runtests
        make -C tests/validation/BasicPythonTest runtests
        make -C tests/validation/ExtendedPythonTest runtests
        make -C tests/validation/BasicDateUtilTest runtests
        make -C tests/validation/ExtendedDateUtilTest runtests
